add: sugar for numeric literal conversions as per Dairy-Foundation/Util#1
Dairy-Foundation/Util pull request #2
Opened 2024-03-16 21:44 UTC by dr-hextanium

as per above

2024-03-17 13:29 UTC, Froze-N-Milk requested changes
Small change for angles to handle wrapping

2024-03-17 13:29 UTC, Froze-N-Milk commented on src/main/kotlin/dev/frozenmilk/util/units/angle/Angle.kt
Change these to check if the value fits within the wrapping range, if its out of the range, then make it linear, otherwise wrapping, also explicit versions of these

2024-03-18 01:57 UTC, Froze-N-Milk approved these changes
Could be good to migrate the comments to kdoc, however this is not necessary rn, and i suspect it shall be picked up along with a lot of other things that need kdoc, approved for merge.

2024-03-18 01:58 UTC, merged

2024-03-18 02:01 UTC, dr-hextanium commented
reopening in order to rename `.autoDeg` to `.deg`